using DeepDive.BackgroundProcessing;
using OpenMeteo;
using System.Collections.Concurrent;

string[] russianTowns = new string[]
{
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Kazan",
    "Nizhny Novgorod",
    "Chelyabinsk",
    "Samara",
    "Omsk",
    "Rostov-on-Don",
    "Ufa",
    "Krasnoyarsk",
    "Perm",
    "Voronezh",
    "Volgograd",
    "Krasnodar",
    "Saratov",
    "Tyumen",
    "Tolyatti",
    "Izhevsk",
    "Barnaul",
    "Ulyanovsk",
    "Irkutsk",
    "Khabarovsk",
    "Yaroslavl",
    "Vladivostok",
    "Makhachkala",
    "Tomsk",
    "Orenburg",
    "Kemerovo",
    "Novokuznetsk",
    "Ryazan",
    "Astrakhan",
    "Naberezhnye Chelny",
    "Penza",
    "Lipetsk",
    "Kirov",
    "Cheboksary",
    "Tula",
    "Kaliningrad",
    "Balashikha",
    "Kursk",
    "Stavropol",
    "Ulan-Ude",
    "Sochi",
    "Bryansk",
    "Ivanovo",
    "Magnitogorsk",
    "Tver",
    "Belgorod",
    "Arkhangelsk",
    "Vladimir",
    "Sevastopol",
    "Chita",
    "Grozny",
    "Kaluga",
    "Smolensk",
    "Volzhsky",
    "Murmansk",
    "Vladikavkaz",
    "Saransk",
    "Cherepovets",
    "Orsk",
    "Vologda",
    "Sterlitamak",
    "Kurgan",
    "Kostroma",
    "Taganrog",
    "Petrozavodsk",
    "Nizhnevartovsk",
    "Yoshkar-Ola",
    "Novorossiysk",
    "Syktivkar",
    "Nizhnekamsk",
    "Shakhty",
    "Dzerzhinsk",
    "Orël",
    "Engels",
    "Blagoveshchensk",
    "Rybinsk",
    "Prokopyevsk",
    "Nalchik",
    "Balakovo",
    "Ussuriysk",
    "Stary Oskol",
    "Zlatoust",
    "Mezhdurechensk",
    "Serpukhov",
    "Armavir",
    "Kamensk-Uralsky",
    "Leninsk-Kuznetsky",
    "Severodvinsk",
    "Zelenodolsk"
};

var metoMiner = new MeteoMiner(russianTowns.ToList());
metoMiner.Stop();
metoMiner.Start();

